version: "3.2"
services:
  gui:
    build: gui
    ports:
      - 8444:8444
      - 8447:8447
      - 5800:5800
    environment:
      TZ: "America/Denver"
      USER_ID: 1000
      GROUP_ID: 1000
    sysctls:
      net.ipv6.conf.lo.disable_ipv6: 0
    volumes:
      - gui_config:/config
      - /tub/chia/farmer:/chia/.chia
    restart: unless-stopped

volumes:
  gui_config:

